### ISSUE TITLE
Documentation des configurations des workflows absente

### ISSUE THREAD

**Issue by CedricKaczmarekHPC** [Jarvis-Platform/jarvis-sdk#20]
Je ne trouve pas de docs sur le fichier de configuration des workflow (exemple : workflow-XXXX.json). Je pensais la trouver sur cette page https://jarvis-platform.gitbook.io/home/j.a.r.v.i.s-configuration/table-to-table mais elle ne s'y trouve pas.

**Comment by romone22** [comment]
The documentation is updated on https://support.fashiondata.io/knowledge
