### ISSUE TITLE
How to mix workflow triggering and Scheduling for a table-to-storage configuration ?

### ISSUE THREAD

**Issue by OlivierColin** [Jarvis-Platform/jarvis-sdk#25]
Hi, 

I would like to trigger a storage-to-table execution with a mix of
- event based execution (workflow)
- schedules execution (cron expression in the configuration file)

For example : the storage-to-table configuration A has to be executed 
- the first day of the month
- when the execution of the configuration table-to-table B is over.

**Comment by OlivierColin** [comment]
Tip given by @romone22 : 
- add a schedule task doing nothing 
- add this task as one of the events in the workflow ...

To be tested and documented

**Comment by romone22** [comment]
@OlivierColin, Did you test the tips ?

**Comment by OlivierColin** [comment]
Yes, it did'nt work untill yesterday (not because of the tip ... )

Real test on the 1st day of June !
